export const throwError = async (ctx) => {
    throw new Error("This is some next level error. We have never its like in History!")
}
